include:
    - DataStructure:
        - 2DBIT.cpp:
            - DataStructure/2DBIT.cpp
        - DynamicSegmentTree.cpp:
            - DataStructure/DynamicSegmentTree.cpp
        - PbdsGpHashTable.cpp:
            - DataStructure/PbdsGpHashTable.cpp
        - PbdsPriorityQueue.cpp:
            - DataStructure/PbdsPriorityQueue.cpp
        - PbdsRope.cpp:
            - DataStructure/PbdsRope.cpp
        - PbdsTree.cpp:
            - DataStructure/PbdsTree.cpp
        - PersistentSegmentTree.cpp:
            - DataStructure/PersistentSegmentTree.cpp
        - Treap.cpp:
            - DataStructure/Treap.cpp
    - Math:
        - CRT.cpp:
            - Math/CRT.cpp
        - CountPrimes.cpp:
            - Math/CountPrimes.cpp
        - FFT.cpp:
            - Math/FFT.cpp
        - FWT.cpp:
            - Math/FWT.cpp
        - Formula.tex:
            - Math/Formula.tex
        - Gaussian-Jordan.cpp:
            - Math/Gaussian-Jordan.cpp
        - Generator.cpp:
            - Math/Generator.cpp
        - Inv.cpp:
            - Math/Inv.cpp
        - Lucas.cpp:
            - Math/Lucas.cpp
        - MillerRabin.cpp:
            - Math/MillerRabin.cpp
        - Mu.cpp:
            - Math/Mu.cpp
        - NTT.cpp:
            - Math/NTT.cpp
        - PollardRho.cpp:
            - Math/PollardRho.cpp
        - XorBasis.cpp:
            - Math/XorBasis.cpp
        - mtt.cpp:
            - Math/mtt.cpp
    - String:
        - Booth.cpp:
            - String/Booth.cpp
        - KMP.cpp:
            - String/KMP.cpp
        - LongestPalindrome.cpp:
            - String/LongestPalindrome.cpp
        - Z.cpp:
            - String/Z.cpp
    - Graph:
        - 2-SAT(CSES Planets Cycles).cpp:
            - Graph/2-SAT(CSES Planets Cycles).cpp
        - Dijkstra.cpp:
            - Graph/Dijkstra.cpp
        - Dinic.cpp:
            - Graph/Dinic.cpp
        - MaximumFlow.cpp:
            - Graph/MaximumFlow.cpp
        - SCC.cpp:
            - Graph/SCC.cpp
        - VBCC.cpp:
            - Graph/VBCC.cpp
        - one-degree-cycle(CSES Planets Cycles).cpp:
            - Graph/one-degree-cycle(CSES Planets Cycles).cpp
    - DP:
        - CHO.cpp:
            - DP/CHO.cpp
        - Li-Chao-SegmentTree.cpp:
            - DP/Li-Chao-SegmentTree.cpp
        - SOSDP.cpp:
            - DP/SOSDP.cpp
    - Geometry:
        - 164253Version.cpp:
            - Geometry/164253Version.cpp
        - ConvexHull.cpp:
            - Geometry/ConvexHull.cpp
        - Inside.cpp:
            - Geometry/Inside.cpp
        - Intersect.cpp:
            - Geometry/Intersect.cpp
        - MinimumEuclideanDistance.cpp:
            - Geometry/MinimumEuclideanDistance.cpp
    - Tree:
        - HeavyLightDecomposition(modify-and-query-on-path).cpp:
            - Tree/HeavyLightDecomposition(modify-and-query-on-path).cpp
        - LCA.cpp:
            - Tree/LCA.cpp
    - Misc:
        - BigNum(luoguP1005).cpp:
            - Misc/BigNum(luoguP1005).cpp
        - Tri-search.cpp:
            - Misc/Tri-search.cpp
        - 對拍.md:
            - Misc/對拍.md
    - AnotherVersionDataStructure:
        - BIT.cpp:
            - AnotherVersionDataStructure/BIT.cpp
        - DSU.cpp:
            - AnotherVersionDataStructure/DSU.cpp
        - Treap.cpp:
            - AnotherVersionDataStructure/Treap.cpp
        - Treap但可以多個數縮點(疑似爛的).cpp:
            - AnotherVersionDataStructure/Treap但可以多個數縮點(疑似爛的).cpp
        - 區間插線段單點查詢李超(是爛的).cpp:
            - AnotherVersionDataStructure/區間插線段單點查詢李超(是爛的).cpp
        - 單點修改動態開點線段樹.cpp:
            - AnotherVersionDataStructure/單點修改動態開點線段樹.cpp
        - 單點修改無懶標線段樹.cpp:
            - AnotherVersionDataStructure/單點修改無懶標線段樹.cpp
        - 懶標線段樹.cpp:
            - AnotherVersionDataStructure/懶標線段樹.cpp
        - 純直線單點查詢李超.cpp:
            - AnotherVersionDataStructure/純直線單點查詢李超.cpp
    - AnotherVersionMath:
        - CRT(luoguVersion).cpp:
            - AnotherVersionMath/CRT(luoguVersion).cpp
        - PollardRho.cpp:
            - AnotherVersionMath/PollardRho.cpp
        - 快速冪.cpp:
            - AnotherVersionMath/快速冪.cpp
        - 數論.cpp:
            - AnotherVersionMath/數論.cpp
        - 篩法.cpp:
            - AnotherVersionMath/篩法.cpp
    - AnotherVersionString:
        - KMP (2).cpp:
            - AnotherVersionString/KMP (2).cpp
        - KMP.cpp:
            - AnotherVersionString/KMP.cpp
        - Manacher (2).cpp:
            - AnotherVersionString/Manacher (2).cpp
        - Manacher.cpp:
            - AnotherVersionString/Manacher.cpp
        - Z.cpp:
            - AnotherVersionString/Z.cpp
    - AnotherVersionGraph:
        - Dijkstra.cpp:
            - AnotherVersionGraph/Dijkstra.cpp
        - SCC.cpp:
            - AnotherVersionGraph/SCC.cpp
        - cses有向圖基環樹森林.cpp:
            - AnotherVersionGraph/cses有向圖基環樹森林.cpp
    - AnotherVersionGeometry:
        - DynamicHull.cpp:
            - AnotherVersionGeometry/DynamicHull.cpp
    - AnotherVersionTree:
        - LCA.cpp:
            - AnotherVersionTree/LCA.cpp
